### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by CryogenicPlanet** [CryogenicPlanet/oakridge-voting#3]
**All this work given is too be done on the one index.html page**
### Login Window 
1. Design Login Form. Inside Card centred on page
2. Validate Username and Password by using Javascript. [Use This](https://www.w3schools.com/jsref/met_document_getelementbyid.asp)
3. After login make login form card hidden and show the form for the voting [Use this](https://stackoverflow.com/questions/2420135/hide-html-element-by-id)
4. **If you have time** Hash the password and try comparing hashes [Hash Documentation](https://github.com/emn178/js-sha256)

**Comment by hypercosmac** [comment]
I made the login page using cookies. I didn't use Ajax posts and rather used cookies.

**Comment by CryogenicPlanet** [comment]
No problem whatsover as long as it works
