### ISSUE TITLE
Design Voting Form

### ISSUE THREAD

**Issue by CryogenicPlanet** [CryogenicPlanet/oakridge-voting#4]
**All this work given is too be done on the one index.html page**
### Form Window 
1. Design the Card to Centre of Screen using css grid
2. Make two Img class on the same row with half card each
3. One row below make a class with a select box in the middle with both candidate names
4. Make a Submit Button
 #### Making a Form for not prime candidates without image space

**Comment by hypercosmac** [comment]
Could I be assigned to this as well now as I have completed the log-in form?
