### ISSUE TITLE
Ajax Post

### ISSUE THREAD

**Issue by CryogenicPlanet** [CryogenicPlanet/oakridge-voting#5]
**All this work given is too be done on the one index.html page**
### Ajax Post
1. Do an $.ajax post to a site for example to "/temp.php" I will send a echo back if you send { dataSent : "Sent Data" } as one of your variable you are passing.
2. [Use This Resources](https://stackoverflow.com/questions/10214723/jquery-ajax-post-data-in-a-java-servlet)
3. Get all values of form from html to javascript.
4. Send all data voting data via json.

**Comment by gaurangbharti1** [comment]
Found this while researching, might help:
https://www.sitepoint.com/use-jquerys-ajax-function/

**Comment by CryogenicPlanet** [comment]
That is a good enough referance
